#!/usr/bin/env bash
set -euo pipefail

# Run all site-selection UA configs generated by build_site_selection_design.R.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CFG_DIR="${ROOT}/uncertainty/config/generated_site_selection"

if [[ ! -d "${CFG_DIR}" ]]; then
  echo "Config directory not found: ${CFG_DIR}" >&2
  exit 1
fi

shopt -s nullglob
configs=("${CFG_DIR}"/*.yaml)
if [[ ${#configs[@]} -eq 0 ]]; then
  echo "No site-selection UA configs found in ${CFG_DIR}" >&2
  exit 0
fi

for cfg in "${configs[@]}"; do
  echo "Running $(basename "${cfg}")"
  Rscript "${ROOT}/runner.R" "${cfg}"
done
