#!/usr/bin/env Rscript

#' Package disturbance generator outputs into a single GeoPackage.
#'
#' For each selected run folder under dist_rate_scenarios/outputs, this script:
#'   1. Reads all disturbance shapefiles generated by the module.
#'   2. Writes them to a GeoPackage named outputs_<runName>.gpkg.
#'   3. Adds companion layers suffixed with "_newOnly" that contain just the
#'      generated features (baseline footprint removed) for diagnostics.

suppressPackageStartupMessages({
  library(data.table)
  library(sf)
})

sf_use_s2(FALSE)

args <- commandArgs(trailingOnly = FALSE)
scriptFile <- sub("^--file=", "", args[grep("^--file=", args)])
scenarioRoot <- if (length(scriptFile)) {
  normalizePath(dirname(scriptFile), winslash = "/", mustWork = TRUE)
} else {
  normalizePath(getwd(), winslash = "/", mustWork = TRUE)
}
projectRoot <- normalizePath(file.path(scenarioRoot, ".."), winslash = "/", mustWork = TRUE)
syntheticRoot <- Sys.getenv("VALIDATION_SYNTHETIC_ROOT",
                            unset = file.path(projectRoot, "data", "synthetic"))
ratesSyntheticRoot <- file.path(syntheticRoot, "rates")

outputsRoot <- file.path(scenarioRoot, "outputs")
if (!dir.exists(outputsRoot)) stop("Outputs folder not found at ", outputsRoot, call. = FALSE)

candidateBaseline <- c(
  file.path(ratesSyntheticRoot, "medium_aoi_optimal.gpkg"),
  file.path(projectRoot, "validation", "rates", "medium_aoi_optimal.gpkg"),
  file.path(scenarioRoot, "medium_aoi_optimal.gpkg")
)
baselineGpkg <- NULL
for (cand in candidateBaseline) {
  if (file.exists(cand)) {
    baselineGpkg <- cand
    break
  }
}
if (is.null(baselineGpkg)) {
  stop("Unable to locate medium_aoi_optimal.gpkg in data/synthetic/rates or validation/rates.", call. = FALSE)
}
baselineGpkg <- normalizePath(baselineGpkg, winslash = "/", mustWork = TRUE)

packageRoot <- file.path(scenarioRoot, "packaged")
dir.create(packageRoot, recursive = TRUE, showWarnings = FALSE)

parse_run_args <- function() {
  runArgs <- args[grepl("^--run=", args)]
  if (length(runArgs)) {
    runs <- trimws(sub("^--run=", "", runArgs))
    runs <- runs[nzchar(runs)]
    if (!length(runs)) stop("No run names supplied via --run=", call. = FALSE)
    return(unique(runs))
  }
  trailing <- commandArgs(trailingOnly = TRUE)
  trailing <- trailing[nzchar(trailing)]
  if (length(trailing)) return(unique(trailing))
  dirs <- dir(outputsRoot, full.names = FALSE)
  dirs <- dirs[file.info(file.path(outputsRoot, dirs))$isdir]
  if (!length(dirs)) stop("No run folders found under ", outputsRoot, call. = FALSE)
  dirs
}

runs <- parse_run_args()

pkg_message <- function(...) cat(sprintf("%s %s\n", format(Sys.time(), "%H:%M:%S"), paste0(...)))

make_clean_layer_name <- function(runName, filePath) {
  base <- sub("\\.shp$", "", basename(filePath))
  base <- sub(paste0("_", runName, "$"), "", base)
  parts <- strsplit(base, "_", fixed = TRUE)[[1]]
  if (length(parts) < 4) return(base)
  dataClass <- paste(parts[3:(length(parts) - 1)], collapse = "_")
  period <- parts[length(parts)]
  paste(dataClass, period, sep = "_")
}

extract_data_class <- function(runName, filePath) {
  base <- sub("\\.shp$", "", basename(filePath))
  base <- sub(paste0("_", runName, "$"), "", base)
  parts <- strsplit(base, "_", fixed = TRUE)[[1]]
  if (length(parts) < 4) return(NA_character_)
  paste(parts[3:(length(parts) - 1)], collapse = "_")
}

extract_period <- function(runName, filePath) {
  base <- sub("\\.shp$", "", basename(filePath))
  base <- sub(paste0("_", runName, "$"), "", base)
  parts <- strsplit(base, "_", fixed = TRUE)[[1]]
  if (length(parts) < 4) return(NA_character_)
  parts[length(parts)]
}

compute_new_only <- function(outputVec, baselineVec) {
  if (is.null(baselineVec) || nrow(baselineVec) == 0L) {
    return(outputVec)
  }
  geomType <- unique(as.character(sf::st_geometry_type(outputVec)))
  if (!any(geomType %in% c("POLYGON", "MULTIPOLYGON"))) {
    return(NULL)
  }
  baseUnion <- tryCatch(sf::st_union(baselineVec), error = function(e) NULL)
  if (is.null(baseUnion) || sf::st_is_empty(baseUnion)) return(outputVec)
  pieces <- lapply(seq_len(nrow(outputVec)), function(i) {
    geom <- sf::st_geometry(outputVec)[i]
    diff <- tryCatch(sf::st_difference(geom, baseUnion), error = function(e) NULL)
    if (is.null(diff) || length(diff) == 0) return(NULL)
    empties <- sf::st_is_empty(diff)
    if (length(empties) && all(!is.na(empties) & empties)) return(NULL)
    sf::st_sf(source_row = i, geometry = diff)
  })
  pieces <- Filter(Negate(is.null), pieces)
  if (!length(pieces)) return(NULL)
  do.call(rbind, pieces)
}

compute_line_diff <- function(outputVec, baselineVec, buffer_width = 20) {
  if (nrow(outputVec) == 0L) return(NULL)
  if (is.null(baselineVec) || nrow(baselineVec) == 0L) return(outputVec)
  out_buf <- tryCatch(sf::st_buffer(outputVec, dist = buffer_width, endCapStyle = "FLAT"), error = function(e) NULL)
  base_buf <- tryCatch(sf::st_buffer(baselineVec, dist = buffer_width, endCapStyle = "FLAT"), error = function(e) NULL)
  if (is.null(out_buf) || is.null(base_buf)) return(NULL)
  base_union <- tryCatch(sf::st_union(base_buf), error = function(e) NULL)
  if (is.null(base_union)) return(outputVec)
  diff_poly <- tryCatch(sf::st_difference(out_buf, base_union), error = function(e) NULL)
  if (is.null(diff_poly) || all(sf::st_is_empty(diff_poly))) return(NULL)
  mask <- tryCatch(sf::st_union(diff_poly), error = function(e) NULL)
  if (is.null(mask) || sf::st_is_empty(mask)) return(NULL)
  diff_lines <- tryCatch(sf::st_intersection(outputVec, mask), error = function(e) NULL)
  if (is.null(diff_lines) || nrow(diff_lines) == 0L) return(NULL)
  diff_lines
}

process_run <- function(runId) {
  pkg_message("Packaging run ", runId)
  runDir <- file.path(outputsRoot, runId)
  if (!dir.exists(runDir)) {
    warning("Run folder not found: ", runDir, call. = FALSE)
    return(NULL)
  }
  shpFiles <- list.files(runDir, pattern = "\\.shp$", full.names = TRUE)
  if (!length(shpFiles)) {
    warning("No shapefiles found in ", runDir, call. = FALSE)
    return(NULL)
  }
  outGpkg <- file.path(packageRoot, paste0("outputs_", runId, ".gpkg"))
  if (file.exists(outGpkg)) file.remove(outGpkg)
  # Clean up possible WAL/SHM from previous gpkgs
  walPath <- paste0(outGpkg, "-wal")
  shmPath <- paste0(outGpkg, "-shm")
  if (file.exists(walPath)) file.remove(walPath)
  if (file.exists(shmPath)) file.remove(shmPath)
  written <- character()
  for (shp in shpFiles) {
    sf_obj <- tryCatch(sf::read_sf(shp), error = function(e) {
      warning("Failed to read ", shp, ": ", e$message, call. = FALSE)
      NULL
    })
    if (is.null(sf_obj) || nrow(sf_obj) == 0L) next
    cleanName <- make_clean_layer_name(runId, shp)
    dataClass <- extract_data_class(runId, shp)
    period <- extract_period(runId, shp)
    sf_obj <- tryCatch(sf::st_transform(sf_obj, 3347), error = function(e) sf_obj)
    layerExists <- file.exists(outGpkg) && cleanName %in% sf::st_layers(outGpkg)$name
    if (layerExists) {
      sf::st_write(sf_obj, outGpkg, layer = cleanName,
                   delete_layer = TRUE, append = FALSE, quiet = TRUE)
    } else {
      append <- file.exists(outGpkg)
      sf::st_write(sf_obj, outGpkg, layer = cleanName,
                   append = append, quiet = TRUE)
    }
    written <- union(written, cleanName)
    baseline <- NULL
    if (!is.na(dataClass) && period != "IC") {
      baseline <- tryCatch(sf::read_sf(baselineGpkg, layer = dataClass), error = function(e) NULL)
      if (!is.null(baseline)) {
        baseline <- tryCatch(sf::st_transform(baseline, sf::st_crs(sf_obj)), error = function(e) baseline)
      }
    }
    geomType <- unique(as.character(sf::st_geometry_type(sf_obj)))
    newOnly <- if (!is.null(baseline)) {
      if (any(geomType %in% c("LINESTRING", "MULTILINESTRING"))) {
        compute_line_diff(sf_obj, baseline)
      } else {
        compute_new_only(sf_obj, baseline)
      }
    } else sf_obj
    if (!is.null(newOnly) && nrow(newOnly) > 0L) {
      newName <- paste0(cleanName, "_newOnly")
      layerExists <- file.exists(outGpkg) && newName %in% sf::st_layers(outGpkg)$name
      if (layerExists) {
        sf::st_write(newOnly, outGpkg, layer = newName,
                     delete_layer = TRUE, append = FALSE, quiet = TRUE)
      } else {
        append <- file.exists(outGpkg)
        sf::st_write(newOnly, outGpkg, layer = newName,
                     append = append, quiet = TRUE)
      }
      written <- union(written, newName)
    }
  }
  # Append baseline (potential) layers for reference
  baseLayers <- sf::st_layers(baselineGpkg)$name
  if (length(baseLayers)) {
    for (layerName in baseLayers) {
      sf_baseline <- tryCatch(sf::read_sf(baselineGpkg, layer = layerName), error = function(e) NULL)
      if (is.null(sf_baseline) || nrow(sf_baseline) == 0L) next
      sf_baseline <- tryCatch(sf::st_transform(sf_baseline, 3347), error = function(e) sf_baseline)
      outLayer <- paste0("baseline_", layerName)
      layerExists <- file.exists(outGpkg) && outLayer %in% sf::st_layers(outGpkg)$name
      if (layerExists) {
        sf::st_write(sf_baseline, outGpkg, layer = outLayer,
                     delete_layer = TRUE, append = FALSE, quiet = TRUE)
      } else {
        append <- file.exists(outGpkg)
        sf::st_write(sf_baseline, outGpkg, layer = outLayer,
                     append = append, quiet = TRUE)
      }
      written <- union(written, outLayer)
    }
  }
  runDataPath <- file.path(projectRoot, "scratch", "run_data.csv")
  if (file.exists(runDataPath)) {
    runData <- tryCatch(data.table::fread(runDataPath), error = function(e) NULL)
    if (!is.null(runData) && "runName" %in% names(runData)) {
      run_id <- runId
      runRows <- runData[runName == run_id]
      if (nrow(runRows)) {
        outCsv <- file.path(packageRoot, paste0("outputs_", runId, "_run_data.csv"))
        data.table::fwrite(runRows, outCsv)
        pkg_message("Run metadata written: ", outCsv)
      } else {
        pkg_message("No run_data rows found for ", runId)
      }
    } else {
      warning("run_data.csv missing runName column or failed to read; skipping run metadata export.", call. = FALSE)
    }
  } else {
    pkg_message("run_data.csv not found; skipping run metadata export")
  }
  pkg_message("GeoPackage written: ", outGpkg)
  outGpkg
}

results <- lapply(runs, process_run)
pkg_message("Finished packaging ", sum(!is.null(results)), " run(s).")
